### ISSUE TITLE
Can't install node-expat dep

### ISSUE THREAD

**Issue by gerbil** [cjoakim/tcx-js#1]
Hi, i was unable to install tcx-js using npm cause of node-expat node-gyp rebuild error.

**Comment by cjoakim** [comment]
gerbil - I was just able to install tcx-js and node-expat on another project; see output below.  You might want to follow-up with the node-expat folks.

package.json contains:
    "tcx-js": "~0.1.2"

[~/github/node-api]$ npm install
\
> node-expat@2.3.13 install /Users/cjoakim/github/node-api/node_modules/tcx-js/node_modules/node-expat
> node-gyp rebuild

  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlparse.o
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmltok.o
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlrole.o
  LIBTOOL-STATIC Release/libexpat.a
  CXX(target) Release/obj.target/node_expat/node-expat.o
  SOLINK_MODULE(target) Release/node_expat.node
tcx-js@0.1.2 node_modules/tcx-js
├── m26-js@0.2.0
├── sb-js@0.1.1 (path@0.11.14)
└── node-expat@2.3.13 (bindings@1.2.1, nan@2.2.1)

**Comment by gerbil** [comment]
Thnx, i'm using tcxparse now.

**Comment by cjoakim** [comment]
tcx-js now no longer uses the node-expat library
